---
- name: Download install script
  get_url:
    url: https://install.raspap.com
    dest: /tmp/raspap-install.sh
    mode: +x

- name: Execute install script
  become: yes
  shell: /tmp/raspap-install.sh -u --yes --openvpn 1 --adblock 0
  register: raspap_install

- debug: var=raspap_install.stdout_lines
