---
- hosts: dockerhost
  roles:
    - common
    - docker
    - docker-compose
    - containers

- hosts: accesspoint
  roles:
    - common
    - accesspoint

- hosts: dashboard
  roles:
    - common
    - dashboard
