version: '2'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable 
    restart: always
    network_mode: host
    volumes:
      - ./data/home-assistant:/config
    environment:
      - TZ=Europe/Dublin

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ./data/plex/library:/config
      - ./data/plex/music:/music

  feedbin-to-todoist:
    container_name: feedbin-to-todoist
    image: dandezille/feedbin-to-todoist
    restart: always
    environment:
      - TICKER_INTERVAL
      - FEEDBIN_USER
      - FEEDBIN_PASSWORD
      - TODOIST_API_KEY

