version: '2'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable 
    restart: always
    network_mode: host
    volumes:
      - ./data/home-assistant:/config
    environment:
      - TZ=Europe/Dublin

