dockerhost:
  hosts:
    nuc:
      ansible_host: 100.70.186.102
      ansible_user: dan

accesspoint:
  hosts:
    pi-router:
      ansible_host: 100.81.246.37
      ansible_user: pi

dashboard:
  hosts:
    pi-leo:
      ansible_host: 100.74.88.12
      ansible_user: pi

