all:
  hosts:
    argon:
      ansible_host: argon.narwhal-major.ts.net
      ansible_user: ubuntu
    barium:
      ansible_host: barium.narwhal-major.ts.net
      ansible_user: ubuntu
    nuc:
      ansible_host: nuc.narwhal-major.ts.net
      ansible_user: dan
      deploy_dir: ~/docker

