all:
  hosts:
    argon:
      ansible_host: argon.narwhal-major.ts.net
      ansible_user: pi
    nuc:
      ansible_host: nuc.narwhal-major.ts.net
      ansible_user: dan
      deploy_dir: ~/docker

