all:
  hosts:
    nuc:
      ansible_host: 100.70.186.102
      ansible_user: dan
      deploy_dir: ~/docker
    pi-leo:
      ansible_host: 100.74.88.12
      ansible_user: pi
    ddz-pihole:
      ansible_host: 100.88.192.40
      ansible_user: root

