---
- name: Install tailscale requirements
  become: yes
  apt:
    pkg:
      - apt-transport-https

- name: Get lsb_release
  shell: lsb_release -cs
  register: lsb_release

- name: Add tailscale repo key
  become: yes
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{lsb_release.stdout}}.gpg
    state: present

- name: Add tailscale repo
  become: yes
  apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{lsb_release.stdout}} main"
    state: present

- name: Install tailscale
  become: yes
  apt:
    pkg:
      - tailscale
    update_cache: yes

