version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data

  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  plex:
    container_name: plex
    image: ghcr.io/linuxserver/plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - ./data/plex/library:/config
      - ./data/plex/music:/music

  feedbin-to-todoist:
    container_name: feedbin-to-todoist
    image: dandezille/feedbin-to-todoist
    restart: unless-stopped
    environment:
      - TICKER_INTERVAL
      - FEEDBIN_USER
      - FEEDBIN_PASSWORD
      - TODOIST_API_KEY

  syncthing:
    container_name: syncthing
    image: ghcr.io/linuxserver/syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/syncthing/config:/config
      - ./data/syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

