version: "3"

networks:
  dns-ext: 
    ipam:
      config:
        - subnet: 172.28.240.0/24
  dns-int: 
    ipam:
      config:
        - subnet: 172.28.241.0/24

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data

  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  feedbin-to-todoist:
    container_name: feedbin-to-todoist
    image: dandezille/feedbin-to-todoist
    restart: unless-stopped
    environment:
      - TICKER_INTERVAL
      - FEEDBIN_USER
      - FEEDBIN_PASSWORD
      - TODOIST_API_KEY

  syncthing:
    container_name: syncthing
    image: ghcr.io/linuxserver/syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/syncthing/config:/config
      - ./data/syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

  samba:
    container_name: samba
    image: dperson/samba
    restart: unless-stopped
    read_only: true
    stdin_open: true
    tty: true
    environment:
      - TZ=Europe/London
      - SHARE=media;/media
      - USERID=1000
      - GROUPID=1000
      - GLOBAL=client min protocol = NT1
      - GLOBAL=server min protocol = NT1
      - GLOBAL2=ntlm auth ntlmv1-permitted
    volumes:
      - ./media:/media:ro
    ports:
      - 139:139
      - 445:445
    tmpfs:
      - /tmp

  coredns:
    container_name: coredns
    image: coredns/coredns
    restart: unless-stopped
    networks:
      dns-int:
        ipv4_address: 172.28.241.8
    volumes:
      - ./Corefile:/Corefile:ro

  pihole:
    container_name: pihole
    image: pihole/pihole
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - DNS1=172.28.241.8
      - DNS2=172.28.241.8
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - ./data/pihole:/etc/pihole:rw
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 80:80
    networks:
      dns-ext:
      dns-int:
    dns:
      - 172.28.241.8
    depends_on:
      - coredns

