---
- name: Copy files
  copy:
    src: '{{ role_path }}/files/'
    dest: '{{ deploy_dir }}'

- name: Start containers
  docker_compose:
    project_src: '{{ deploy_dir }}'
    remove_orphans: yes
    pull: yes
    restarted: yes
