---
- name: Copy compose file
  copy:
    src: ./docker-compose.yml
    dest: ~/docker/

- name: Copy .env file
  copy:
    src: .env
    dest: ~/docker/

- name: Setup containers
  docker_compose:
    project_src: ~/docker
    remove_orphans: yes
    pull: yes

