---
- name: Add docker repo key
  become: yes
  vars:
    distro: "{{ansible_facts.distribution | lower}}"
  apt_key:
    url: https://download.docker.com/linux/{{distro}}/gpg
    state: present

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- debug: var=deb_architecture.stdout

- name: Add docker repo
  become: yes
  vars:
    - distro: "{{ansible_facts.distribution | lower}}"
    - release: "{{ansible_facts.distribution_release | lower}}"
    - url: https://download.docker.com/linux
    - arch: "{{deb_architecture.stdout}}"
  apt_repository:
    repo: 'deb [arch={{arch}}] {{url}}/{{distro}} {{release}} stable'
    state: present


